import { useMemo, useState } from "react";
import { Plus, Trash2, Download, Copy, Check } from "lucide-react";

type Route = { id: string; method: string; path: string; status: number; delay: number; body: string };
const uid = () => Math.random().toString(36).slice(2, 9);

const INITIAL: Route[] = [
  { id: uid(), method: "GET", path: "/api/users", status: 200, delay: 120, body: `[{ "id": 1, "name": "Ada" }]` },
  { id: uid(), method: "POST", path: "/api/session", status: 201, delay: 300, body: `{ "token": "mock-token" }` },
];

function buildWorker(routes: Route[]) {
  const table = routes.map((r) => `  {
    method: ${JSON.stringify(r.method)},
    pattern: new URLPattern({ pathname: ${JSON.stringify(r.path)} }),
    status: ${r.status},
    delay: ${r.delay},
    body: ${JSON.stringify(r.body)},
  }`).join(",\n");

  return `// Generated by Proforma Hub — Service Worker Mock API
const ROUTES = [
${table}
];

self.addEventListener("install", () => self.skipWaiting());
self.addEventListener("activate", (e) => e.waitUntil(self.clients.claim()));

self.addEventListener("fetch", (event) => {
  const req = event.request;
  const match = ROUTES.find(
    (r) => r.method === req.method && r.pattern.test(req.url)
  );
  if (!match) return;
  event.respondWith(
    new Promise((resolve) =>
      setTimeout(
        () =>
          resolve(
            new Response(match.body, {
              status: match.status,
              headers: { "Content-Type": "application/json" },
            })
          ),
        match.delay
      )
    )
  );
});
`;
}

const REGISTER = `if ("serviceWorker" in navigator) {
  navigator.serviceWorker.register("/sw.js").then(() => {
    console.log("Mock API worker registered");
  });
}`;

export default function MockApi() {
  const [routes, setRoutes] = useState<Route[]>(INITIAL);
  const [copied, setCopied] = useState(false);
  const sw = useMemo(() => buildWorker(routes), [routes]);

  return (
    <div className="grid gap-4 lg:grid-cols-2">
      <div className="glass p-5">
        <div className="flex items-center justify-between">
          <h3 className="text-sm font-semibold">Mock routes</h3>
          <button onClick={() => setRoutes((p) => [...p, { id: uid(), method: "GET", path: "/api/new", status: 200, delay: 100, body: "{}" }])} className="inline-flex items-center gap-1 text-xs text-[color:var(--neon-blue)]">
            <Plus className="h-3.5 w-3.5" /> Add route
          </button>
        </div>
        <div className="mt-4 space-y-3">
          {routes.map((r) => (
            <div key={r.id} className="rounded-xl border border-border bg-surface/40 p-3">
              <div className="flex flex-wrap items-center gap-2">
                <select value={r.method} onChange={(e) => setRoutes((p) => p.map((x) => x.id === r.id ? { ...x, method: e.target.value } : x))} className="rounded-lg border border-input bg-surface px-2 py-1.5 text-xs outline-none [&>option]:bg-[color:var(--popover)]">
                  {["GET", "POST", "PUT", "PATCH", "DELETE"].map((m) => <option key={m}>{m}</option>)}
                </select>
                <input value={r.path} onChange={(e) => setRoutes((p) => p.map((x) => x.id === r.id ? { ...x, path: e.target.value } : x))} className="input flex-1 min-w-[8rem]" />
                <input type="number" value={r.status} onChange={(e) => setRoutes((p) => p.map((x) => x.id === r.id ? { ...x, status: Number(e.target.value) } : x))} className="input w-20" />
                <input type="number" value={r.delay} onChange={(e) => setRoutes((p) => p.map((x) => x.id === r.id ? { ...x, delay: Number(e.target.value) } : x))} className="input w-20" title="Delay ms" />
                <button onClick={() => setRoutes((p) => p.filter((x) => x.id !== r.id))} className="text-muted-foreground hover:text-[color:var(--destructive)]"><Trash2 className="h-4 w-4" /></button>
              </div>
              <JsonBody
                value={r.body}
                onChange={(v) => setRoutes((p) => p.map((x) => x.id === r.id ? { ...x, body: v } : x))}
              />

            </div>
          ))}
        </div>
      </div>

      <div className="space-y-4">
        <div className="glass p-5">
          <div className="flex items-center justify-between">
            <h3 className="text-sm font-semibold">sw.js</h3>
            <div className="flex gap-2">
              <button onClick={() => { navigator.clipboard.writeText(sw); setCopied(true); setTimeout(() => setCopied(false), 1500); }} className="inline-flex items-center gap-1.5 rounded-lg border border-border bg-surface px-2.5 py-1.5 text-xs font-semibold hover:bg-surface-2">
                {copied ? <Check className="h-3.5 w-3.5 text-[color:var(--neon-green)]" /> : <Copy className="h-3.5 w-3.5" />}
              </button>
              <button
                onClick={() => {
                  const url = URL.createObjectURL(new Blob([sw], { type: "text/javascript" }));
                  const a = document.createElement("a"); a.href = url; a.download = "sw.js"; a.click(); URL.revokeObjectURL(url);
                }}
                className="inline-flex items-center gap-1.5 rounded-lg bg-[image:var(--gradient-neon)] px-3 py-1.5 text-xs font-semibold text-[color:var(--primary-foreground)] hover:opacity-90"
              >
                <Download className="h-3.5 w-3.5" /> Download
              </button>
            </div>
          </div>
          <pre className="mt-3 max-h-80 overflow-auto rounded-lg bg-surface p-3 font-mono text-[11px] leading-relaxed">{sw}</pre>
        </div>
        <div className="glass p-5">
          <h3 className="text-sm font-semibold">Register it</h3>
          <p className="mt-1 text-xs text-muted-foreground">Place <code className="font-mono">sw.js</code> at your app root, then add this snippet.</p>
          <pre className="mt-3 overflow-auto rounded-lg bg-surface p-3 font-mono text-[11px] leading-relaxed">{REGISTER}</pre>
        </div>
      </div>
    </div>
  );
}

function JsonBody({ value, onChange }: { value: string; onChange: (v: string) => void }) {
  const [expanded, setExpanded] = useState(true);
  const error = useMemo(() => {
    if (!value.trim()) return "Body is empty";
    try { JSON.parse(value); return ""; } catch (e) { return (e as Error).message; }
  }, [value]);

  return (
    <div className="mt-2">
      <div className="flex flex-wrap items-center gap-2">
        <span className="text-[11px] font-semibold text-muted-foreground">Response JSON</span>
        {error
          ? <span className="inline-flex items-center gap-1 text-[10px] text-[color:var(--destructive)]"><AlertTriangle className="h-3 w-3" /> {error}</span>
          : <span className="inline-flex items-center gap-1 text-[10px] text-[color:var(--neon-green)]"><Check className="h-3 w-3" /> valid JSON</span>}
        <button
          onClick={() => { try { onChange(JSON.stringify(JSON.parse(value), null, 2)); } catch { /* ignore */ } }}
          disabled={!!error}
          className="ml-auto rounded border border-border px-2 py-0.5 text-[10px] font-semibold hover:bg-surface-2 disabled:opacity-40"
        >
          Format
        </button>
        <button onClick={() => setExpanded((v) => !v)} className="rounded border border-border px-2 py-0.5 text-[10px] font-semibold hover:bg-surface-2">
          {expanded ? "Collapse" : "Expand editor"}
        </button>
      </div>
      <textarea
        value={value}
        rows={expanded ? 12 : 3}
        spellCheck={false}
        placeholder={'{\n  "items": [\n    { "id": 1 }\n  ]\n}'}
        onChange={(e) => onChange(e.target.value)}
        className={`mt-2 w-full resize-y rounded-lg border bg-surface p-2 font-mono text-[11px] leading-relaxed outline-none ${error ? "border-[color:var(--destructive)]/60" : "border-input focus:border-[color:var(--neon-blue)]"}`}
      />
    </div>
  );
}
